library:
  source-dirs: src
tests:
  learning-haskell-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-haskell
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- QuickCheck
- containers
- parsec
- base >= 4.7 && < 5
name: learning-haskell
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/learning-haskell
license: BSD3
executables:
  learning-haskell-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-haskell
description: Please see the README on GitHub at <https://github.com/githubuser/learning-haskell#readme>
